SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM (
    SELECT FISH_NAME
    FROM FISH_NAME_INFO N 
        INNER JOIN FISH_INFO I 
        ON N.FISH_TYPE = I.FISH_TYPE
) AS T
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC;