SELECT 
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM (
    SELECT 
        COALESCE(LENGTH, 10) AS LENGTH,
        FISH_TYPE
    FROM FISH_INFO
) AS T
GROUP BY FISH_TYPE HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;